### PR TITLE
Switch to the new minimal terraform-registry-address API

### PR DESCRIPTION
**Pull request by radeksimko**
Depends on https://github.com/hashicorp/terraform-registry-address/pull/12

### CODE REVIEW

**Comment by radeksimko** [comment]
Not sure what the CI failures are about - they look unrelated to this PR - let me know if they are, I can take a deeper look.

**Review by detro — COMMENTED** [review]
LGTM

**Comment by detro** [comment]
Mmm, I think the paths used when running `terraform-provider-corner` tests need to be updated. Let me see if I can find an example PR.

**Comment by detro** [comment]
Here are the necessary changes: https://github.com/hashicorp/terraform-plugin-framework/pull/385/files

**Comment by radeksimko** [comment]
@detro I addressed the failures by adjusting the paths in the workflow file which seemed sufficient to get it all green.

PTAL

**Review by bflad — APPROVED** [review]
Looks good to me 🚀

**Comment by bflad** [comment]
@radeksimko are you going to cut a tagged release first or would you like these merged first? Thanks!

**Comment by radeksimko** [comment]
@bflad I'm planning to merge all the PRs first and possibly still try to see if TF Registry itself could also consume it - which may still affect the API - but I might end up leaving that one for v2 if it gets too hairy.

**Pull request merged**
