### PR TITLE
tfprotov5+tfprotov6: Initial provider defined functions implementation

### PR DESCRIPTION
**Pull request by bflad**
Reference: https://github.com/hashicorp/terraform/pull/34383
Reference: https://github.com/hashicorp/terraform-plugin-go/issues/353

The next version of the plugin protocol (5.5/6.5) includes support for provider defined functions. This change introduces the initial implementation of that support including:

- Updated Protocol Buffers definitions
- Re-generated Protocol Buffers Go code
- Initial implementations of `tfprotov5` and `tfprotov6` package abstractions and wiring between those abstractions and the Protocol Buffers generated Go code
- Initial implementations of `tfprotov5/tf5server` and `tfprotov6/tf6server` for the new `GetFunctions` and `CallFunction` RPCs

This temporarily will not require `ProviderServer` implementations to include `FunctionServer` implementation, however that change will occur in a subsequent release.

### CODE REVIEW

**Review by bendbennett — APPROVED** [review]
LGTM 🚀

**Comment by bflad** [comment]
FYI as I mentioned earlier today, I'm going to try to spread the `ProviderServer` change over two releases: an initial "optional" interface that servers can pick up to remove the "breaking change" here, then later on, remove that optional interface and make it required as part of the `ProviderServer` interface.

**Comment by bflad** [comment]
@bendbennett here's what I did if you want to check it: https://github.com/hashicorp/terraform-plugin-go/pull/351/commits/fb1d856be38c4fccc56fb61bcf6559aefb3a1460

**Review by austinvalle — APPROVED** [review]
LGTM 🚀 🚀

**Pull request merged**
