### PR TITLE
tfprotov5+tfprotov6: Require FunctionServer in ProviderServer and MoveResourceState in ResourceServer

### LINKED ISSUE #353: tfprotov5+tfprotov6: Add FunctionServer to ProviderServer interface
### terraform-plugin-go version

```
v0.20.0 (not yet released)
```

### Description

The upcoming v0.20.0 release will contain the `tfprotov5` and `tfprotov6` package `FunctionServer` interface, which contains the two RPC function handlers for provider defined functions. Rather than immediately requiring all downstream SDK implementations to implement this functionality immediately by requiring `FunctionServer` as part of `ProviderServer`, it seems ideal if we can stagger the releases between introducing and supporting the new `FunctionServer` bits then having a followup release that makes the implementation required with the "breaking change" to match the intended design of this Go module to always require all provider implementations to fully implement the protocol.

For provider developers, this type of terraform-plugin-go change previously surfaced as confusing `missing method XXX` when updating only some dependencies of terraform-plugin-framework, terraform-plugin-mux, terraform-plugin-sdk, or terraform-plugin-testing where terraform-plugin-go required the additional `ProviderServer` bits, but with the newer setup there can at least be better chance that particular update issue won't occur for them.

### Proposal

In the first release, temporarily check for `FunctionServer` interface implementation in `tfprotov5/tf5server` and `tfprotov6/tf6server` package `GetFunctions` and `CallFunction` implementations. If found, pass request downstream. If not found, raise an error diagnostic.

In the second release (part of this issue), add `FunctionServer` interface in `ProviderServer` implementation. Remove temporary `FunctionServer` interface checks and associated error diagnostic.

### References

- https://github.com/hashicorp/terraform-plugin-framework/issues/861
- https://github.com/hashicorp/terraform-plugin-testing/issues/185

### LINKED ISSUE #363: tfprotov5+tfprotov6: Move MoveResourceState method into ResourceServer
### terraform-plugin-go version

```
v0.21.0 (not yet released)
```

### Description

The upcoming v0.21.0 release will contain the `tfprotov5` and `tfprotov6` package `ResourceServerWithMoveResourceState` temporary interface, which contains the `MoveResourceState` RPC function handler. Rather than immediately requiring all downstream SDK implementations to implement this functionality immediately by requiring `MoveResourceState` as part of `ResourceServer`, it seems ideal if we can stagger the releases between introducing and supporting the new `MoveResourceState` bits then having a followup release that makes the implementation required with the "breaking change" to match the intended design of this Go module to always require all provider implementations to fully implement the protocol.

For provider developers, this type of terraform-plugin-go change previously surfaced as confusing `missing method XXX` when updating only some dependencies of terraform-plugin-framework, terraform-plugin-mux, terraform-plugin-sdk, or terraform-plugin-testing where terraform-plugin-go required the additional `ResourceServer` bits, but with the newer setup there can at least be better chance that particular update issue won't occur for them and changelog can reference the minimum SDK versions.

### Proposal

Move the `MoveResourceState` method from `ResourceServerWithMoveResourceState` to `ResourceServer`. Remove temporary `ResourceServerWithMoveResourceState` interface, logic referencing it, and associated error diagnostics when it was missing in the server implementations.

### References

- #362

### PR DESCRIPTION
**Pull request by bflad**
Closes #353
Closes #363

This removes the temporary handling to smoothly release the new Terraform 1.8 and later RPC handling for provider servers. These changes codify this Go module's desired design that it reflects the protocol via its required implementations.

### CODE REVIEW

**Comment by bflad** [comment]
Submitted https://github.com/hashicorp/terraform-provider-corner/pull/223 to make CI happier 😄

**Review by bendbennett — APPROVED** [review]
LGTM 🚀

**Comment by bflad** [comment]
Looks like this will need to be done over two releases because terraform-plugin-mux required calling `MoveResourceState`, which required directly referencing the temporary `ResourceServerWithMoveResourceState` interface. This PR will be updated to contain `MoveResourceState` method in _both_ interfaces, then we can remove `ResourceServerWithMoveResourceState` later.

Maybe it can be a takeaway for future prerelease RPCs to only implement them in mux if _absolutely_ necessary. The problem is that `hashicorp/aws` and other large providers tend to be a target for those features and use mux. We could consider whether mux should still remain a separate Go module, instead moving all those packages under the scope of this Go module. Mux is stable enough, low level enough, and also allows breaking changes. We would just need to sort out with the web platform team the website documentation since it references the terraform-plugin-mux repository directly.

**Comment by bflad** [comment]
Updated this PR to reinstate `ResourceServerWithMoveResourceServer` a little longer. Created https://github.com/hashicorp/terraform-plugin-go/issues/389 for eventual followup once this is released and terraform-plugin-mux is upgraded and released.

**Comment by bflad** [comment]
Given this functionality is now GA in Terraform 1.8 and the interfaces have been out for a month+, going to update and merge this for release at any time.

**Pull request merged**
